# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Set the working directory inside the container
WORKDIR /data/db

# Expose the MongoDB default port
EXPOSE 27017

# Start MongoDB server when the container launches
CMD ["mongod"]

